-- MySQL Script generated by MySQL Workbench
-- Wed Apr 30 01:07:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Databasenewsstand
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Databasenewsstand
-- -----------------------------------------------------
CREATE Database newsstand DEFAULT CHARACTER SET utf8 ;
USE newsstand ;

-- -----------------------------------------------------
-- Table newsstand.roles
-- -----------------------------------------------------
CREATE TABLE  newsstand.roles (
  role_id INT NOT NULL AUTO_INCREMENT,
  type VARCHAR(45) NOT NULL,
  PRIMARY KEY (role_id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.users
-- -----------------------------------------------------
CREATE TABLE  newsstand.users (
  user_id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  email VARCHAR(75) NOT NULL,
  password VARCHAR(75) NOT NULL,
  profile_photo VARCHAR(75) NULL,
  role_id INT NOT NULL,
  join_date DATE,
  last_login DATETIME,
  PRIMARY KEY (user_id),
  UNIQUE INDEX email_UNIQUE (email ASC) ,
  INDEX fk_users_roles1_idx (role_id ASC) ,
  UNIQUE INDEX user_id_UNIQUE (user_id ASC) ,
  UNIQUE INDEX profile_photo_UNIQUE (profile_photo ASC) ,
  CONSTRAINT fk_users_roles1
    FOREIGN KEY (role_id)
    REFERENCES newsstand.roles (role_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.authors
-- -----------------------------------------------------
CREATE TABLE  newsstand.authors (
  author_id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  email VARCHAR(75) NOT NULL,
  bio VARCHAR(255) NOT NULL,
  PRIMARY KEY (author_id),
  UNIQUE INDEX author_id_UNIQUE (author_id ASC) ,
  UNIQUE INDEX email_UNIQUE (email ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.contents
-- -----------------------------------------------------
CREATE TABLE  newsstand.contents (
  content_id INT NOT NULL AUTO_INCREMENT,
  type VARCHAR(45) NOT NULL,
  title VARCHAR(100) NOT NULL,
  publish_date DATE NOT NULL,
  description VARCHAR(255) NULL,
  cover_img VARCHAR(45) NOT NULL,
  PRIMARY KEY (content_id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.headers
-- -----------------------------------------------------
CREATE TABLE  newsstand.headers (
  header_id INT NOT NULL AUTO_INCREMENT,
  header_name VARCHAR(50) NULL,
  subscription_price DOUBLE,
  PRIMARY KEY (header_id),
  UNIQUE INDEX header_name_UNIQUE (header_name ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.magazines
-- -----------------------------------------------------
CREATE TABLE  newsstand.magazines (
  magazine_id INT NOT NULL,
  num_of_download INT NOT NULL,
  normal_path VARCHAR(75) NOT NULL,
  optimized_path VARCHAR(75) NULL,
  header_id INT NOT NULL,
  price DOUBLE NOT NULL,
  PRIMARY KEY (magazine_id),
  INDEX Fk_header_idx (header_id ASC) ,
  CONSTRAINT fk_kk
    FOREIGN KEY (magazine_id)
    REFERENCES newsstand.contents (content_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT Fk_header
    FOREIGN KEY (header_id)
    REFERENCES newsstand.headers (header_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.categories
-- -----------------------------------------------------
CREATE TABLE  newsstand.categories (
  category_id INT NOT NULL AUTO_INCREMENT,
  type VARCHAR(45) NOT NULL,
  PRIMARY KEY (category_id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.articles
-- -----------------------------------------------------
CREATE TABLE  newsstand.article (
  article_id INT NOT NULL,
  total_reads INT NULL,
  author_id INT NOT NULL,
  PRIMARY KEY (article_id),
  INDEX fk_article_author1_idx (author_id ASC) ,
  CONSTRAINT fk_article_author1
    FOREIGN KEY (author_id)
    REFERENCES newsstand.authors (author_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_khh
    FOREIGN KEY (article_id)
    REFERENCES newsstand.contents (content_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.content_categories
-- -----------------------------------------------------
CREATE TABLE  newsstand.content_categories (
  category_id INT NOT NULL,
  content_id INT NOT NULL,
  PRIMARY KEY (category_id, content_id),
  INDEX fk_ctegory_has_article_ctegory1_idx (category_id ASC) ,
  INDEX fk_ctegory_has_article_article1_idx (content_id ASC) ,
  CONSTRAINT fk_ctegory_has_article_ctegory1
    FOREIGN KEY (category_id)
    REFERENCES newsstand.categories (category_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ctegory_has_article_article1
    FOREIGN KEY (content_id)
    REFERENCES newsstand.contents (content_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.bodies
-- -----------------------------------------------------
CREATE TABLE  newsstand.bodies (
  body_id INT NOT NULL AUTO_INCREMENT,
  audio_path VARCHAR(75) NULL,
  body LONGTEXT NOT NULL,
  language VARCHAR(45) NOT NULL,
  article_id INT NOT NULL,
  PRIMARY KEY (body_id, article_id),
  INDEX fk_body_article1_idx (article_id ASC) ,
  CONSTRAINT fk_body_article1
    FOREIGN KEY (article_id)
    REFERENCES newsstand.article (article_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.comments
-- -----------------------------------------------------
CREATE TABLE  newsstand.comments (
  comment_id INT NOT NULL AUTO_INCREMENT,
  content VARCHAR(255) NOT NULL,
  creation_time DATETIME NOT NULL,
  user_id INT NOT NULL,
  content_id INT NOT NULL,
  PRIMARY KEY (comment_id),
  INDEX fk_comment_users1_idx (user_id ASC) ,
  INDEX fk_comment_article1_idx (content_id ASC) ,
  CONSTRAINT fk_comment_users1
    FOREIGN KEY (user_id)
    REFERENCES newsstand.users (user_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_comment_article1
    FOREIGN KEY (content_id)
    REFERENCES newsstand.contents (content_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.subscriptions
-- -----------------------------------------------------
CREATE TABLE  newsstand.subscriptions (
  sub_id INT NOT NULL AUTO_INCREMENT,
  auto_renewal INT NOT NULL,
  start_date DATE NOT NULL,
  type VARCHAR(45) NOT NULL,
  user_id INT NOT NULL,
  header_id INT NULL,
  magazine_id INT NULL,
  PRIMARY KEY (sub_id),
  INDEX fk_subscribtion_users1_idx (user_id ASC) ,
  INDEX fk2_idx (header_id ASC) ,
  INDEX fk_singlemag_idx (magazine_id ASC) , 
  CONSTRAINT fk_subscribtion_users1
    FOREIGN KEY (user_id)
    REFERENCES newsstand.users (user_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_singlemag
    FOREIGN KEY (magazine_id)
    REFERENCES newsstand.magazines (magazine_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk2
    FOREIGN KEY (header_id)
    REFERENCES newsstand.headers (header_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.reacts
-- -----------------------------------------------------
CREATE TABLE  newsstand.reacts (
  react_type INT NOT NULL,
  content_id INT NOT NULL,
  user_id INT NOT NULL,
  PRIMARY KEY (content_id, user_id),
  INDEX fk_idx (user_id ASC) ,
  CONSTRAINT fk_react_article1
    FOREIGN KEY (content_id)
    REFERENCES newsstand.contents (content_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk
    FOREIGN KEY (user_id)
    REFERENCES newsstand.users (user_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.reports
-- -----------------------------------------------------
CREATE TABLE  newsstand.reports (
  report_id INT NOT NULL AUTO_INCREMENT,
  report_date DATE NOT NULL,
  report_reason VARCHAR(100) NOT NULL,
  user_id INT NOT NULL,
  content_id INT NOT NULL,
  PRIMARY KEY (report_id),
  INDEX fk_idx (content_id ASC) ,
  INDEX ffl_idx (user_id ASC) ,
  CONSTRAINT fk_uu
    FOREIGN KEY (content_id)
    REFERENCES newsstand.contents (content_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT ffl_fjhjh
    FOREIGN KEY (user_id)
    REFERENCES newsstand.users (user_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.special_editions
-- -----------------------------------------------------
CREATE TABLE  newsstand.special_editions (
  special_id INT NULL,
  header_id INT NOT NULL,
  highest_price DOUBLE NULL,
  user_id INT NULL,
  PRIMARY KEY (special_id),
  INDEX fk_idx (user_id ASC) ,
  INDEX fk3_fhu_idx (header_id ASC) ,
  CONSTRAINT fk_gg
    FOREIGN KEY (user_id)
    REFERENCES newsstand.users (user_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk2_gf
    FOREIGN KEY (special_id)
    REFERENCES newsstand.contents (content_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk3_fhuu
    FOREIGN KEY (header_id)
    REFERENCES newsstand.headers (header_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.ratings
-- -----------------------------------------------------
CREATE TABLE  newsstand.ratings (
  rating_id INT NOT NULL AUTO_INCREMENT,
  rating INT NOT NULL,
  rating_date DATE NOT NULL,
  opinion VARCHAR(255) NULL,
  user_id INT NOT NULL,
  PRIMARY KEY (rating_id),
  INDEX fl_idx (user_id ASC) ,
  CONSTRAINT fl
    FOREIGN KEY (user_id)
    REFERENCES newsstand.users (user_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
	check (rating between 1 and 10))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.payments
-- -----------------------------------------------------
CREATE TABLE  newsstand.payments (
  payment_id INT NOT NULL AUTO_INCREMENT,
  amount DOUBLE NULL,
  time DATETIME NULL,
  sub_id INT NOT NULL,
  PRIMARY KEY (payment_id),
  INDEX fk1_idx (sub_id ASC) ,
  CONSTRAINT fk1_utd
    FOREIGN KEY (sub_id)
    REFERENCES newsstand.subscriptions (sub_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table newsstand.saved_contents
-- -----------------------------------------------------
CREATE TABLE  newsstand.saved_contents (
  user_id INT NOT NULL,
  content_id INT NOT NULL,
  place VARCHAR(45) NOT NULL,
  date DATETIME NOT NULL,
  PRIMARY KEY (content_id, place, user_id),
  CONSTRAINT ffk1
    FOREIGN KEY (content_id)
    REFERENCES newsstand.contents (content_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT ffk2
    FOREIGN KEY (user_id)
    REFERENCES newsstand.users (user_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
